# Generated by Django 4.0.4 on 2022-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.IntegerField(null=True)),
                ('start_payment_time', models.CharField(max_length=40, null=True)),
                ('process_payment_time', models.CharField(max_length=40, null=True)),
                ('final', models.CharField(max_length=20, null=True)),
                ('status_message', models.TextField(default='')),
                ('provide_error_text', models.TextField(default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='NEW', max_length=20)),
                ('fio', models.CharField(max_length=150)),
                ('card_data', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('metadata', models.TextField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('p12cert', models.FileField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
