# Generated by Django 4.0.4 on 2022-06-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcert',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcert',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
