# Generated by Django 4.0.4 on 2022-06-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_user_paymentcert_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentCert',
        ),
    ]
