# Generated by Django 4.0.4 on 2022-07-15 11:50

from django.db import migrations, models
import payments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_paymentcert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fio',
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_data',
            field=models.CharField(max_length=20, validators=[payments.validators.is_credit_card_validator]),
        ),
    ]
