version: '3.9'


volumes:
  postgresdata:
  rabbitdata:


services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn fiz_pay_back.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - app/.env.prod
    depends_on:
      - db
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    volumes:
      - rabbitdata:/bitnami
    ports:
      - 15672:15672
      - 5672:5672


  db:
    image: postgres:14-alpine3.16
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - app/.env.prod.db



