version: '3.9'


volumes:
  postgresdata:
  rabbitdata:


services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq


  rabbitmq:
    image: bitnami/rabbitmq:3.9-debian-11
    restart: always
    volumes:
      - rabbitdata:/bitnami
    ports:
      - 15672:15672
      - 5672:5672

  db:
    image: postgres:14-alpine3.16
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev.db



