version: '3.9'


volumes:
  postgresdata:
  rabbitdata:


services:

  app:
    build: .
    command: python manage.py runserver --noreload
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=my_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RABBIT_HOST=rabbitmq
      - PAYMENT_WORKER_COUNT=1
      - SECRET_KEY=temp
    depends_on:
      - postgres
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
      - rabbitdata:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: my_database
    ports:
      - 5432:5432



